default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['db_user'] || 'root'  %>
  password: <%= ENV['db_pass'] || 'root' %>
  host: <%= ENV['db_host'] || 'localhost' %>
  port: 5432

development:
  <<: *default
  database: open_trello_development

test:
  <<: *default
  database: open_trello_test

production:
  <<: *default
  database: open_trello_production
